version: '2'
services:
  rabbitmq-service:
    image: rabbitmq:3-management
    ports:
        - "5672:5672"
        - "15672:15672"
  eureka-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./eureka-server/build/libs:/app
    command: java -jar /app/eureka-server.jar --server.port=8761
    ports:
      - "8761:8761"
  mongodb-service:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
    command: mongod --smallfiles
  user-registration-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./user-registration-service/build/libs:/app
    command: java -jar /app/user-registration-service-0.1.0.jar --spring.profiles.active=enableEureka --eureka.client.serviceUrl.defaultZone=http://192.168.99.100:8761/eureka/
    ports:
      - "8081:8080"
    links:
      - rabbitmq-service
      - eureka-service
      - mongodb-service
    depends_on:
      - rabbitmq-service
      - eureka-service
      - mongodb-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://192.168.99.100/userregistration
      SPRING_RABBITMQ_HOST: 192.168.99.100
      SPRING_APPLICATION_NAME: user-registration-service
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://192.168.99.100:8761/eureka/
  pub1:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./pub/build/libs:/app
    command: java -jar /app/pub-0.1.0.jar --spring.profiles.active=enableEureka --eureka.client.serviceUrl.defaultZone=http://192.168.99.100/eureka/
    ports:
      - "8082:8080"
    links:
      - rabbitmq-service
      - eureka-service
    depends_on:
      - rabbitmq-service
      - eureka-service
    environment:
      SPRING_RABBITMQ_HOST: 192.168.99.100
      SPRING_APPLICATION_NAME: pub
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://192.168.99.100:8761/eureka/
  pub2:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./pub/build/libs:/app
    command: java -jar /app/pub-0.1.0.jar --spring.profiles.active=enableEureka --eureka.client.serviceUrl.defaultZone=http://192.168.99.100:8761/eureka/
    ports:
      - "8084:8080"
    links:
      - rabbitmq-service
      - eureka-service
    depends_on:
      - rabbitmq-service
      - eureka-service
    environment:
      SPRING_RABBITMQ_HOST: 192.168.99.100
      SPRING_APPLICATION_NAME: pub
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://192.168.99.100:8761/eureka/
  pub3:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./pub/build/libs:/app
    command: java -jar /app/pub-0.1.0.jar --spring.profiles.active=enableEureka --eureka.client.serviceUrl.defaultZone=http://192.168.99.100:8761/eureka/
    ports:
      - "8085:8080"
    links:
      - rabbitmq-service
      - eureka-service
    depends_on:
      - rabbitmq-service
      - eureka-service
    environment:
      SPRING_RABBITMQ_HOST: 192.168.99.100
      SPRING_APPLICATION_NAME: pub
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://192.168.99.100:8761/eureka/
  ppv-adapter1:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./ppv-adapter/build/libs:/app
    command: java -jar /app/ppv-adapter-0.1.0.jar --spring.profiles.active=enableEureka --eureka.client.serviceUrl.defaultZone=http://192.168.99.100/eureka/
    ports:
      - "8086:8080"
    links:
      - rabbitmq-service
      - eureka-service
    depends_on:
      - rabbitmq-service
      - eureka-service
    environment:
      SPRING_RABBITMQ_HOST: 192.168.99.100
      SPRING_APPLICATION_NAME: ppv-adapter
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://192.168.99.100:8761/eureka/
  ppv-adapter2:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./ppv-adapter/build/libs:/app
    command: java -jar /app/ppv-adapter-0.1.0.jar --spring.profiles.active=enableEureka --eureka.client.serviceUrl.defaultZone=http://192.168.99.100:8761/eureka/
    ports:
      - "8087:8080"
    links:
      - rabbitmq-service
      - eureka-service
    depends_on:
      - rabbitmq-service
      - eureka-service
    environment:
      SPRING_RABBITMQ_HOST: 192.168.99.100
      SPRING_APPLICATION_NAME: ppv-adapter
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://192.168.99.100:8761/eureka/
  ppv-adapter3:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./pub/build/libs:/app
    command: java -jar /app/ppv-adapter-0.1.0.jar --spring.profiles.active=enableEureka --eureka.client.serviceUrl.defaultZone=http://192.168.99.100:8761/eureka/
    ports:
      - "8088:8080"
    links:
      - rabbitmq-service
      - eureka-service
    depends_on:
      - rabbitmq-service
      - eureka-service
    environment:
      SPRING_RABBITMQ_HOST: 192.168.99.100
      SPRING_APPLICATION_NAME: ppv-adapter
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://192.168.99.100:8761/eureka/
