server:
    port: 8081
spring:
  #application:
    #name: userregistration
  #profiles:
    #active: development,messagesource,mongodb,rabbitmq,swagger2
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: false
      serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/

  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: maxvandewiel